src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Entity\PropertyImage;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("name")
 * @ORM\HasLifecycleCallbacks
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Choice(callback="getHeatsIds", message="Merci de choisi le type de chauffage parmi la liste proposées.")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex(
     *  pattern="/^[0-9]{5}$/",
     *  message="Le code postal doit être un nombre de 5 chiffres"
     * )
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @var PropertyImage|null
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity=PropertyImage::class, mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="property")
     */
    private $contacts;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime);
        $this->options = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify)->slugify($this->getName());
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->getPrice(), 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->getHeat()];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getFormattedAddress($separator = ', ')
    {
        $output = [
            $this->getAddress(),
            $this->getPostalCode() . ' ' . $this->getCity(),
        ];
        return implode($separator, $output);
    }

    /**
     * @return array
     */
    public function getHeatsIds()
    {
        return array_keys(self::HEAT);
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return Collection|PropertyImage[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(PropertyImage $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setProperty($this);
        }

        return $this;
    }

    public function removeImage(PropertyImage $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProperty() === $this) {
                $image->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return ?string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param PropertyImage $image
     * @return self
     */
    public function setImage(PropertyImage $image): self
    {
        $this->image = $image;
        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setProperty($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getProperty() === $this) {
                $contact->setProperty(null);
            }
        }

        return $this;
    }

    /**    
     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->setUpdatedAt(new \DateTime);
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime|null $updatedAt
     * @return self
     */
    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use App\Form\PropertyImageType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getHeatChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
            ->add('images', CollectionType::class, [
                'entry_type' => PropertyImageType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    /**
     * @return array
     */
    private function getHeatChoices()
    {
        $output = [];
        foreach (Property::HEAT as $key => $value) {
            $output[$value] = $key;
        }
        return $output;
    }
}

src/Controller/Admin/PropertyController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Property;
use App\Form\PropertyType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Liip\ImagineBundle\Imagine\Cache\CacheManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    private $repository;
    private $em;

    public function __construct(PropertyRepository $propertyRepository, EntityManagerInterface $em)
    {
        $this->repository = $propertyRepository;
        $this->em = $em;
    }

    public function index()
    {
        $properties = $this->repository->findAll();
        return $this->render('admin/property/index.html.twig', ['properties' => $properties]);
    }

    public function edit(Property $property, Request $request)
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $propertyImages = $property->getImages();
            foreach ($propertyImages as $key => $propertyImage) {
                if ($propertyImage->getProperty() && !$propertyImage->getImageName()) {
                    $property->removeImage($propertyImage);
                } else {
                    $propertyImage->setProperty($property);
                    $propertyImages->set($key, $propertyImage);
                }
            }

            $this->em->flush();
            $this->addFlash('success', 'Le bien a bien été modifié');
            return $this->redirectToRoute('admin.property.edit', ['id' => $property->getId()]);
        }

        return $this->render('admin/property/edit.html.twig', [
            'property' => $property,
            'form' => $form->createView()
        ]);
    }


    public function new(Request $request)
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $propertyImages = $property->getImages();
            foreach ($propertyImages as $key => $propertyImage) {
                $propertyImage->setProperty($property);
                $propertyImages->set($key, $propertyImage);
            }

            $this->em->persist($property);
            $this->em->flush();
            $this->addFlash('success', 'Le bien a bien été créé');
            return $this->redirectToRoute('admin.property.edit', ['id' => $property->getId()]);
        }

        return $this->render('admin/property/new.html.twig', [
            'property' => $property,
            'form' => $form->createView()
        ]);
    }


    public function delete(Property $property, Request $request)
    {
        if ($this->isCsrfTokenValid('delete' . $property->getId(), $request->get('_token'))) {
            $this->em->remove($property);
            $this->em->flush();
            $this->addFlash('success', 'Le bien a bien été supprimé');
        }
        return $this->redirectToRoute('admin.property.index');
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    private $propertyRepository = null;

    public function __construct(PropertyRepository $propertyRepository)
    {
        $this->propertyRepository = $propertyRepository;
    }

    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $this->propertyRepository->paginateAllVisible($search, $request->query->getInt('page', 1)),
            'form' => $form->createView()
        ]);
    }


    /**
     * @param Property $property
     * @param string $slug
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $contactNotification): Response
    {
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug(),
            ], 301);
        }

        $contact = new Contact;
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactNotification->notify($contact);
            $this->addFlash('success', 'Votre email a bien été envoyé');
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug(),
            ]);
        }

        return $this->render('property/show.html.twig', [
            'current_menu' => 'properties',
            'property' => $property,
            'form' => $form->createView()
        ]);
    }
}

templates/property/_property.html.twig
{% cache "property" ~ property.id ~ ";" ~ property.updatedAt.timestamp|default(date('2018-01-01 00:00:00').timestamp) %}
<div class="cols">
	<div class="card shadow-sm">
		<a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">
			{% if property.getImage %}
				<img src="{{ vich_uploader_asset(property.getImage, 'imageFile') | imagine_filter('thumb') }}" alt="" style="width:100%" />
			{% else %}
				<svg class="bd-placeholder-img card-img-top" width="100%" style="height:27vh" xmlns="http://www.w3.org/2000/svg" role="img"
					aria-label="Placeholder: Thumbnail" preserveaspectratio="xMidYMid slice" focusable="false">
					<title>Placeholder</title>
					<rect width="100%" height="100%" fill="#55595c"></rect>
					<text x="50%" y="50%" fill="#eceeef" dy=".3em" style="text-anchor:middle">Thumbnail</text>
				</svg>
			{% endif %}
		</a>		
	</div>
	<div class="card-body">
		<div class="card-title">
			{{ property.surface }} m² - 
			<a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.name }}</a>
		</div>

		<div class="text-primary fw-bold" style="font-size:2rem">{{ property.formattedPrice }} €</div>
	</div>
</div>
{% endcache %}

templates/property/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Mes biens
{% endblock %}

{% block body %}
	<div class="container mt-3 mb-3">
		<h1>Les biens</h1>
	</div>

	<div class="p-5 mb-4 bg-light rounded-3">
		<div class="container-fluid py-5">
			{{ form_start(form) }}
				<div class="row">
					<div class="col-md-3">{{ form_row(form.minSurface) }}</div>
					<div class="col-md-3">{{ form_row(form.maxPrice) }}</div>
					<div class="col-md-3">{{ form_row(form.options) }}</div>
					<div class="col-md-3"><input type="submit" class="btn btn-primary" value="Rechercher"></div>
				</div>				
			{{ form_end(form) }}
		
		</div>
	</div>

	<div class="container">
		<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
			{% for property in properties %}
				{% include "property/_property.html.twig" %}
			{% endfor %}
		</div>
	</div>

	
	<div class="container">
		<div class="pagination">
			{{ knp_pagination_render(properties) }}
		</div>
	</div>
	
	
{% endblock %}

templates/property/property_card.html.twig
<div class="cols">
	<div class="card shadow-sm">
		<a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">
			{% if property.getFirstImage %}
				<img src="{{ vich_uploader_asset(property.getFirstImage, 'imageFile') | imagine_filter('thumb') }}" alt="" style="width:100%" />
			{% else %}
				<svg class="bd-placeholder-img card-img-top" width="100%" style="height:27vh" xmlns="http://www.w3.org/2000/svg" role="img"
					aria-label="Placeholder: Thumbnail" preserveaspectratio="xMidYMid slice" focusable="false">
					<title>Placeholder</title>
					<rect width="100%" height="100%" fill="#55595c"></rect>
					<text x="50%" y="50%" fill="#eceeef" dy=".3em" style="text-anchor:middle">Thumbnail</text>
				</svg>
			{% endif %}
		</a>		
	</div>
	<div class="card-body">
		<div class="card-title">
			{{ property.surface }} m² - 
			<a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.name }}</a>
		</div>

		<div class="text-primary fw-bold" style="font-size:2rem">{{ property.formattedPrice }} €</div>
	</div>
</div>

templates/property/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{ property.name }}
{% endblock %}

{% block stylesheets %}
<style>
	.swiper {
		width: 800px;
		height: 600px;
	}
</style>
{% endblock %}

{% block body %}
	<div class="p-5 mb-4 bg-light rounded-3">
		<div class="container-fluid py-5">

			{% for message in app.flashes('success') %}
				<div class="alert alert-success">{{ message }}</div>
			{% endfor %}

			<div class="row">
				<div class="col-md-8">
					<div class="swiper">
						<div class="swiper-wrapper">
							{% for propertyImage in property.getImages %}
							<div class="swiper-slide">
								<img src="{{ vich_uploader_asset(propertyImage, 'imageFile') | imagine_filter('medium') }}" alt=""
									style="width:100%" />
							</div>
							{% endfor %}							
						</div>	
						<div class="swiper-button-prev"></div>
						<div class="swiper-button-next"></div>
					</div>					
				</div>

				<div class="col-md-4">
					<h1>{{ property.name }}</h1>
					<h2>
						{{ property.rooms}}
						pièces -
						{{ property.surface }}
						m²
					</h2>
					<div class="text-primary fw-bold" style="font-size:2rem">{{ property.formattedPrice }}
						€</div>
					<a href="#" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %}style="display:none"{% endif %}>Contact</a>
					<div id="contactForm" class="mt-4" {% if not form.vars.submitted %}style="display:none"{% endif %} >
						{{ form_start(form) }}
							<div class="row">
								<div class="col">{{ form_row(form.firstname) }}</div>
								<div class="col">{{ form_row(form.lastname) }}</div>
							</div>
							<div class="row">
								<div class="col">{{ form_row(form.email) }}</div>
								<div class="col">{{ form_row(form.phoneNumber) }}</div>
							</div>
							{{ form_rest(form) }}
							<div class="form-group">
								<button class="btn btn-primary">Envoyer</button>
							</div>
						{{ form_end(form) }}
					</div>
				</div>

			</div>

		</div>
	</div>


	<div class="container">
		<p>{{ property.description | nl2br }}</p>

		<div class="row">
			<div class="col-md-8">
				<h2>Caractéristiques</h2>
				<table class="table table-striped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ property.surface }}
							m²</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ property.rooms }}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{ property.bedrooms }}</td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{ property.floor }}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{ property.heatType }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Spécificités</h2>
				<ul class="list-group">
					{% for option in property.options %}
						<li class="list-group-item">{{ option.name }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}